services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=secretnote
      - POSTGRES_USER=secretnote
      - POSTGRES_PASSWORD=secretnote
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  web:
    build: .
    command: >
      sh -c "until nc -z db 5432; do echo waiting for db; sleep 1; done &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn secret_notes_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://secretnote:secretnote@db:5432/secretnote
      - DEBUG=False
    depends_on:
      - db

volumes:
  static_volume: